language: "perl"

perl:
  - "5.22"
  - "5.14"


services:


env:


sudo: false

addons:
    apt:
        packages:
        - unzip

before_install:
    - wget http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz
    - mkdir bioperl-live && tar zxvf BioPerl-1.6.1.tar.gz -C bioperl-live --strip-components 1
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone -b master --depth=1 https://github.com/samtools/htslib.git
    - cd htslib
    - make prefix=~/biodbhts install
    - export HTSLIB_DIR=
    - cd ..

install:
    # manually install items from cpanfile so we can skip BioPerl
    - cpanm -f -n Carp
    - cpanm -f -n Test::Most
    - cpanm -f -n Module::Build
    - cpanm -f -n Log::Log4perl
    - cpanm -f -n Try::Tiny
    # install the modules just used here
    - cpanm --notest Perl::Tidy
    - cpanm --notest Test::Code::TidyAll
    - export PERL5LIB=$PERL5LIB:$PWD/bioperl-live
    - perl Build.PL --prefix=~/biodbhts
    - ./Build
    - ./Build test

script: "./travisci/harness.sh"


notifications:
  email:
    on_success: always
    on_failure: always
