---
abstract: 'Perl interface to HTS library for DNA sequencing'
author:
  - 'Rishi Nag'
build_requires:
  ExtUtils::CBuilder: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-HTSTools
provides:
  Bio::DB::HTS:
    file: lib/Bio/DB/HTS.pm
    version: '1.00'
  Bio::DB::HTS::AlignWrapper:
    file: lib/Bio/DB/HTS/AlignWrapper.pm
  Bio::DB::HTS::Alignment:
    file: lib/Bio/DB/HTS/Alignment.pm
  Bio::DB::HTS::Constants:
    file: lib/Bio/DB/HTS/Constants.pm
  Bio::DB::HTS::Fai:
    file: lib/Bio/DB/HTS.pm
  Bio::DB::HTS::FetchIterator:
    file: lib/Bio/DB/HTS/FetchIterator.pm
  Bio::DB::HTS::Pileup:
    file: lib/Bio/DB/HTS/Pileup.pm
  Bio::DB::HTS::PileupWrapper:
    file: lib/Bio/DB/HTS/PileupWrapper.pm
  Bio::DB::HTS::Query:
    file: lib/Bio/DB/HTS/Query.pm
  Bio::DB::HTS::ReadIterator:
    file: lib/Bio/DB/HTS/ReadIterator.pm
  Bio::DB::HTS::Segment:
    file: lib/Bio/DB/HTS/Segment.pm
  Bio::DB::HTS::Segment::Iterator:
    file: lib/Bio/DB/HTS/Segment.pm
  Bio::DB::HTS::SplitAlignmentPart:
    file: lib/Bio/DB/HTS/AlignWrapper.pm
  Bio::DB::HTS::Target:
    file: lib/Bio/DB/HTS/Target.pm
  Bio::DB::HTSfile:
    file: lib/Bio/DB/HTS.pm
  Bio::SeqFeature::Coverage:
    file: lib/Bio/DB/HTS.pm
requires:
  Bio::Root::Version: '1.006009001'
  perl: '5.008'
version: '1.00'
